# Generated by Django 3.1.5 on 2021-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_extendeduser_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
